####################################################################################################
# FEAT hake survey: comparing EchoPro and Echopop report outputs across years
# ---------------------------------------------------------------------------
# This ingests the reports generated by Echopop and compares them with those produced by EchoPro.
# This script requires that the reports either be in separate folders, or have unique names that
# differentiate the EchoPro and Echopop reports.
# ==================================================================================================
# PARAMETER ENTRY
# ---------------
from datetime import date
from pathlib import Path
from typing import Callable
from echopop.reports import compare
import yaml
import matplotlib.pyplot as plt

# ==================================================================================================
# USER CONFIGURATION
# ------------------
# USER FLAGS
EXTRAP_FLAG=True #True or False
STRATA_TYPE="ks" #ks or inpfc
# LOAD IN CONFIG FILES
config_output = yaml.safe_load(Path("workflow/comparison_configs/comparison_output_config.yaml").read_text(encoding="utf-8"))
COMPARISON_ROOT=config_output["cross_year_comparison_output_path"]
# OUTPUT FIGURE FILEPATH

SAVE_FILEPATH = Path(
    #f"C:/Data/EchopopData/cross_year_comparisons_{date.today().strftime("%Y%m%d")}.png"
    #f"C:/Data/EchopopData/cross_year_comparisons_{date.today().strftime("%Y%m%d")}.png"
    COMPARISON_ROOT +"/cross_year_comparisons/cross_year_comparisons_"+f"{date.today().strftime("%Y%m%d")}.png"
)
SAVE_FILEPATH_NO_DATE = Path(
    #f"C:/Data/EchopopData/cross_year_comparisons_{date.today().strftime("%Y%m%d")}.png"
    #f"C:/Data/EchopopData/cross_year_comparisons_{date.today().strftime("%Y%m%d")}.png"
    COMPARISON_ROOT +"/cross_year_comparisons/cross_year_comparisons.png"
)

# PARQUET CACHE DIRECTORY
# Set to None to disable caching entirely.
#CACHE_DIR = Path("C:/Data/EchopopData/.cache")
CACHE_DIR=None

# YEARS TO PROCESS
#YEARS = [1995, 1998, 2001, 2003, 2005, 2007, 2009, 2011, 2012, 2013, 2015, 2017, 2019, 2021]
YEARS = [2015,2017,2019,2021]

# DIRECTORY TEMPLATES
# -------------------
# Define functions that accept a year (int) and return a Path to the report directory.
# Adjust these to match your local folder structure. Examples:
#   lambda year: Path(f"C:/Data/EchopopData/reports/{year}/echopro/")
#   lambda year: Path(f"C:/Data/EchopopData/echopop_{year}/reports_echopro")
# ECHOPRO_ROOT: Callable[[int], Path] = lambda year: Path(
#     f"C:/Data/EchopopData/file_all_years_update_20260303/{year}/output_echopro"
# )
# ECHOPOP_ROOT: Callable[[int], Path] = lambda year: Path(
#     f"C:/Data/EchopopData/file_all_years_update_20260303/{year}/output_echopop"
# )

if EXTRAP_FLAG==True:
    Exname="KwE"
else:
    Exname="KnE"
#REPORTS_DIR = Path("C:/rthomas/Projects/EchoPop_validation/Reports/"+runyearstr+"/EchoPop/"+STRATA_TYPE+"/"+Exname+"/" )
#ECHOPOP_ROOT_test = lambda year: Path(f"C:/rthomas/Projects/EchoPop_validation/Reports/{year}/EchoPop/"+STRATA_TYPE)
#ECHOPOP_ROOT = lambda year: Path(f"C:/rthomas/Projects/EchoPop_validation/Reports/{year}/EchoPop/"+STRATA_TYPE+"/"+Exname+"/")
#ECHOPOP_ROOT = lambda year: Path(f"C:/rthomas/Projects/EchoPop_validation/Reports/{year}/EchoPop/"+STRATA_TYPE+"/"+Exname+"/")
#ECHOPOP_ROOT = lambda year: Path(config_output["reports_out_base"]+"/{year}/EchoPop/"+STRATA_TYPE+"/"+Exname+"/")
ECHOPOP_ROOT: Callable[[int], Path] = lambda year:  Path(
    config_output["reports_out_base"]+f"/{year}/EchoPop/"+STRATA_TYPE+"/"+Exname+"/"
)
ECHOPRO_ROOT: Callable[[int], Path] = lambda year:  Path(
    config_output["reports_out_base"]+f"/{year}/EchoPro_2022/"+STRATA_TYPE+"/"+Exname+"/"
)


# FILENAME PATTERNS
# -----------------
# Both Echopop and EchoPro filenames are matched via regex pattern. An exact filename string is
# also valid and will match only that file. Each pattern must match exactly one file per directory.
# Examples:
#   Exact:  "transect_population_results_full.xlsx"
#   Regex:  r"^EchoPro_kriged_output(?:-.*)?_0\.xlsx$"
# ECHOPOP_PATTERNS = {
#     "transect": r"transect_population_results_full\.xlsx",
#     "kriging": r"kriged_biomass_mesh_full\.xlsx",
# }
# RT set the report patterns for EchoPop to match EchoPro
ECHOPOP_PATTERNS = {
    "transect": r"^EchoPop_un-kriged_output(?:-.*)?_0\.xlsx$",
    "kriging": r"^EchoPop_kriged_output(?:-.*)?_0\.xlsx$",
}
ECHOPRO_PATTERNS = {
    "transect": r"^EchoPro_un-kriged_output(?:-.*)?_0\.xlsx$",
    "kriging": r"^EchoPro_kriged_output(?:-.*)?_0\.xlsx$",
}

# PARALLELIZATION (optional)
# --------------------------
# Set to None to load files sequentially (default, safest across all OS).
# Set to a positive integer (e.g. 8) to enable parallel loading via a thread pool.
MAX_WORKERS = None

# ==================================================================================================
# LOAD ALL DATA
ECHOPRO_DATASETS, ECHOPOP_DATASETS = compare.load_all_geodata_reports(
    years=YEARS,
    echopro_root=ECHOPRO_ROOT,
    echopop_root=ECHOPOP_ROOT,
    echopop_patterns=ECHOPOP_PATTERNS,
    echopro_patterns=ECHOPRO_PATTERNS,
    cache_dir=CACHE_DIR,
    max_workers=MAX_WORKERS,
    verbose=True
)

# ==================================================================================================
# COMPUTE DIFFERENCES
differences, pct_diff = compare.compute_dataset_differences(
    echopro_datasets=ECHOPRO_DATASETS,
    echopop_datasets=ECHOPOP_DATASETS,
)

# ==================================================================================================
# PLOT DIFFERENCES [%]

# Turn on interactive mode so plt.show() doesn't block
plt.ion()  

compare.plot_dataset_differences(
    pct_diff,
    save_filepath=SAVE_FILEPATH,
)
# Close the figure window 
plt.close('all') 

#also save a copy without a date so that the latest plot can always be found.
compare.plot_dataset_differences(
    pct_diff,
    save_filepath=SAVE_FILEPATH_NO_DATE,
)
plt.close('all') 
#Turn interactive mode back off
plt.ioff()