mesh_file: krig_grid2_5nm_cut_centroids_2013.xlsx
mesh_sheet: krigedgrid2_5nm_forChu
variogram_parameters_file: default_vario_krig_settings_2021_US&CAN.xlsx
variogram_parameters_sheet: "Sheet1"
isobath_file: transformation_isobath_coordinates.xlsx
isobath_sheet: "Smoothing_EasyKrig"